base_url = "https://pacharanero.github.io/sct"
title = "sct"
description = "A fast, local SNOMED CT toolkit"
theme = "book"
compile_sass = true
build_search_index = true

content_dir = "docs"

[extra]
book_number_chapters = false
book_only_current_section_pages = false
