// SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Full-pipeline end-to-end tests over a committed, fully-synthetic RF2 snapshot
//! (`tests/fixtures/rf2/`, generated by `generate.py` - not real SNOMED content,
//! so licence-free). Each test runs the real `sct ndjson` and `sct sqlite`
//! commands over the fixture, then asserts across every feature: active
//! filtering, GB/US dialect preferred terms, hierarchy, typed relationships,
//! CTV3 maps, refset membership, FTS5 search, the transitive-closure table, and
//! ECL (hierarchy / boolean / refset / attribute refinement).

use rusqlite::Connection;
use sct_rs::commands::ndjson::{self, RefsetMode};
use sct_rs::commands::size;
use sct_rs::commands::sqlite;
use sct_rs::ecl;
use sct_rs::schema::ConceptRecord;
use std::path::{Path, PathBuf};

const EXAMPLE_REFSET: &str = "991381000000107";

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/rf2/SnomedCT_SyntheticTest_PRODUCTION_20260101T120000Z")
}

/// Build NDJSON (at `locale`) and a SQLite DB (with the transitive-closure
/// table) from the fixture into a fresh tempdir. Returns the guard plus paths.
fn build(locale: &str) -> (tempfile::TempDir, PathBuf, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    let db = dir.path().join("syn.db");

    ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: locale.to_string(),
        output: Some(ndjson.clone()),
        include_inactive: false,
        refsets: RefsetMode::Simple,
    })
    .unwrap();

    sqlite::run(sqlite::Args {
        input: ndjson.clone(),
        output: db.clone(),
        transitive_closure: true,
        include_self: false,
    })
    .unwrap();

    (dir, ndjson, db)
}

/// As [`build`] but with `--refsets all`, so the ExtendedMap (ICD-10/OPCS-4) and
/// Association (history) refsets load.
fn build_all(locale: &str) -> (tempfile::TempDir, PathBuf, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    let db = dir.path().join("syn.db");
    ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: locale.to_string(),
        output: Some(ndjson.clone()),
        include_inactive: false,
        refsets: RefsetMode::All,
    })
    .unwrap();
    sqlite::run(sqlite::Args {
        input: ndjson.clone(),
        output: db.clone(),
        transitive_closure: false,
        include_self: false,
    })
    .unwrap();
    (dir, ndjson, db)
}

fn read_records(path: &Path) -> Vec<ConceptRecord> {
    std::fs::read_to_string(path)
        .unwrap()
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.contains("sct_provenance"))
        .map(|l| serde_json::from_str(l).unwrap())
        .collect()
}

fn record<'a>(records: &'a [ConceptRecord], id: &str) -> &'a ConceptRecord {
    records.iter().find(|r| r.id == id).expect("record present")
}

/// Evaluate ECL and return the matching SCTIDs, sorted for comparison.
fn ecl(db: &Path, expr: &str) -> Vec<String> {
    let mut v = ecl::expand_path(db, expr).unwrap();
    v.sort();
    v
}

#[test]
fn extended_maps_load_into_crossmaps() {
    let (_d, ndjson, db) = build_all("en-GB");

    // NDJSON: MI carries an ICD-10 crossmap with its advice preserved.
    let records = read_records(&ndjson);
    let mi = record(&records, "22298006");
    let icd = mi
        .crossmaps
        .iter()
        .find(|m| m.system == "icd10")
        .expect("MI has an ICD-10 crossmap");
    assert_eq!(icd.code, "I219");
    assert_eq!(icd.advice, "ALWAYS I21.9");

    // DB: forward (SNOMED -> ICD-10 / OPCS-4) and reverse (code -> SNOMED).
    let conn = Connection::open(&db).unwrap();
    let ctv3: String = conn
        .query_row(
            "SELECT target_code FROM crossmaps
             WHERE source_system='ctv3' AND source_code='X200' AND target_system='snomed'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(ctv3, "22298006");
    let fwd: String = conn
        .query_row(
            "SELECT target_code FROM crossmaps WHERE source_code='22298006' AND target_system='icd10'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(fwd, "I219");
    let opcs: String = conn
        .query_row(
            "SELECT target_code FROM crossmaps WHERE source_code='80146002' AND target_system='opcs4'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(opcs, "H011");
    // Reverse: which SNOMED concept maps to ICD-10 E10.9 (Type 1 diabetes)?
    let snomed: String = conn
        .query_row(
            "SELECT source_code FROM crossmaps WHERE target_system='icd10' AND target_code='E109'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(snomed, "46635009");
}

#[test]
fn simple_mode_omits_extended_maps() {
    // Default `--refsets simple` loads SimpleMap rows into crossmaps, but must
    // NOT load the heavy ExtendedMap / history data.
    let (_d, _ndjson, db) = build("en-GB");
    let conn = Connection::open(&db).unwrap();
    let simple_maps: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM crossmaps WHERE source_system='ctv3' AND target_system='snomed'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert!(simple_maps > 0);
    let extended_maps: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM crossmaps WHERE source_system='snomed' AND target_system IN ('icd10', 'opcs4')",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(extended_maps, 0);
    let hist: i64 = conn
        .query_row("SELECT COUNT(*) FROM concept_history", [], |r| r.get(0))
        .unwrap();
    assert_eq!(hist, 0);
}

#[test]
fn concept_history_loads_from_associations() {
    let (_d, ndjson, db) = build_all("en-GB");

    // The history sidecar is written next to the NDJSON.
    let sidecar = ndjson.with_file_name("syn.history.ndjson");
    assert!(sidecar.exists(), "history sidecar should be written");

    // Inactive 9468002 forwards to Asthma (same_as) and MI (replaced_by).
    let conn = Connection::open(&db).unwrap();
    let mut rows: Vec<(String, String)> = conn
        .prepare("SELECT association, target_id FROM concept_history WHERE source_id='9468002'")
        .unwrap()
        .query_map([], |r| Ok((r.get(0)?, r.get(1)?)))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    rows.sort();
    assert_eq!(
        rows,
        vec![
            ("replaced_by".to_string(), "22298006".to_string()),
            ("same_as".to_string(), "195967001".to_string()),
        ]
    );
}

#[test]
fn pipeline_filters_inactive_concepts() {
    let (_d, ndjson, _db) = build("en-GB");
    let records = read_records(&ndjson);
    // 23 concepts in the fixture, 1 inactive (9468002) -> 22 active records.
    assert_eq!(records.len(), 22);
    assert!(records.iter().all(|r| r.id != "9468002"));
}

#[test]
fn include_inactive_emits_inactive_concepts() {
    // Regression test for `--include-inactive`. The inactive concept 9468002 was
    // dropped at RF2 load time regardless of the flag; it must now appear, with
    // `active = false` and its term fully populated from its (still-active) FSN.
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: "en-GB".to_string(),
        output: Some(ndjson.clone()),
        include_inactive: true,
        refsets: RefsetMode::Simple,
    })
    .unwrap();

    let records = read_records(&ndjson);
    // All 23 fixture concepts now, exactly one of them inactive.
    assert_eq!(records.len(), 23);
    assert_eq!(records.iter().filter(|r| !r.active).count(), 1);

    let inactive = record(&records, "9468002");
    assert!(!inactive.active);
    assert_eq!(inactive.fsn, "Inactive example disorder (disorder)");
    assert_eq!(inactive.preferred_term, "Inactive example disorder");

    // Active concepts are unaffected: every other record is still active.
    assert!(records
        .iter()
        .filter(|r| r.id != "9468002")
        .all(|r| r.active));
}

#[test]
fn dialect_preferred_terms() {
    let (_g, gb_ndjson, _gdb) = build("en-GB");
    assert_eq!(
        record(&read_records(&gb_ndjson), "80146002").preferred_term,
        "Appendicectomy"
    );

    let (_u, us_ndjson, _udb) = build("en-US");
    assert_eq!(
        record(&read_records(&us_ndjson), "80146002").preferred_term,
        "Appendectomy"
    );
}

#[test]
fn builder_record_shape() {
    let (_d, ndjson, _db) = build("en-GB");
    let records = read_records(&ndjson);

    let mi = record(&records, "22298006");
    assert_eq!(mi.preferred_term, "Myocardial infarction");
    assert_eq!(mi.hierarchy, "Clinical finding");
    assert!(mi.synonyms.contains(&"Heart attack".to_string()));
    assert!(mi.ctv3_codes.contains(&"X200".to_string()));

    // Typed relationships preserved with type SCTID + group (for ECL).
    let has = |t: &str, d: &str| {
        mi.relationships
            .iter()
            .any(|r| r.type_id == t && r.destination_id == d && r.group == 1)
    };
    assert!(has("363698007", "74281007"), "finding site");
    assert!(has("116676008", "55641003"), "associated morphology");

    // Refset membership surfaced on the member records.
    assert!(record(&records, "46635009")
        .refsets
        .contains(&EXAMPLE_REFSET.to_string()));
}

#[test]
fn ecl_hierarchy_boolean_and_refset() {
    let (_d, _ndjson, db) = build("en-GB");

    assert_eq!(ecl(&db, "<<73211009"), ["44054006", "46635009", "73211009"]);
    assert_eq!(ecl(&db, "<73211009"), ["44054006", "46635009"]);
    assert_eq!(
        ecl(&db, ">>46635009"),
        ["138875005", "404684003", "46635009", "73211009"]
    );
    assert_eq!(ecl(&db, "<!73211009"), ["44054006", "46635009"]);
    assert_eq!(ecl(&db, "^991381000000107"), ["44054006", "46635009"]);
    assert_eq!(
        ecl(&db, "<<73211009 MINUS 46635009"),
        ["44054006", "73211009"]
    );
    assert_eq!(ecl(&db, "195967001 OR 22298006"), ["195967001", "22298006"]);
}

#[test]
fn ecl_attribute_refinement() {
    let (_d, _ndjson, db) = build("en-GB");
    // Clinical findings whose finding site is (a descendant-or-self of) Myocardium.
    assert_eq!(
        ecl(&db, "<<404684003 : 363698007 = <<74281007"),
        ["22298006"]
    );
    // Wrong value -> no match.
    assert!(ecl(&db, "<<404684003 : 363698007 = 55641003").is_empty());
}

#[test]
fn sqlite_fts5_maps_relationships_and_tct() {
    let (_d, _ndjson, db) = build("en-GB");
    let conn = Connection::open(&db).unwrap();

    // FTS5 keyword search: "diabetes" hits the parent + both subtypes.
    let mut stmt = conn
        .prepare(
            "SELECT c.id FROM concepts_fts JOIN concepts c ON concepts_fts.rowid = c.rowid
             WHERE concepts_fts MATCH '\"diabetes\"' ORDER BY c.id",
        )
        .unwrap();
    let mut ids: Vec<String> = stmt
        .query_map([], |r| r.get::<_, String>(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    ids.sort();
    assert_eq!(ids, ["44054006", "46635009", "73211009"]);

    // CTV3 reverse map.
    let mapped: String = conn
        .query_row(
            "SELECT concept_id FROM concept_maps WHERE code = 'X200' AND terminology = 'ctv3'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(mapped, "22298006");

    // Typed relationships table (schema v4): MI has its 2 attributes.
    let rel_count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM concept_relationships WHERE source_id = '22298006'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(rel_count, 2);

    // Transitive closure: Type 1 DM has 3 ancestors (DM, Clinical finding, root).
    let anc_count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM concept_ancestors WHERE descendant_id = '46635009'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(anc_count, 3);

    // Refset membership.
    let mut stmt = conn
        .prepare("SELECT referenced_component_id FROM refset_members WHERE refset_id = ?1 ORDER BY referenced_component_id")
        .unwrap();
    let members: Vec<String> = stmt
        .query_map([EXAMPLE_REFSET], |r| r.get::<_, String>(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    assert_eq!(members, ["44054006", "46635009"]);
}

#[test]
fn size_estimate_for_root() {
    let (_d, _ndjson, db) = build("en-GB");
    let conn = Connection::open(&db).unwrap();

    let est = size::estimate_sizes(&conn, "138875005", 50).unwrap();
    assert_eq!(est.subtree_count, est.total_count);
    assert_eq!(est.pct(), 100.0);
    assert!(est.avg_ndjson_bytes > 0);
    assert_eq!(est.sqlite_total, est.total_db_bytes);
    assert!(est.ndjson_total > 0);
}

#[test]
fn size_builds_tct_when_missing() {
    use sct_rs::commands::size::{self, Args};
    use sct_rs::output::OutputFormat;

    let (_d, _ndjson, db) = build("en-GB");

    // Drop the TCT to simulate a database without one.
    {
        let conn = Connection::open(&db).unwrap();
        conn.execute("DROP TABLE concept_ancestors", []).unwrap();
    }

    // Run `sct size --build-tct`, which should rebuild the TCT and proceed.
    let args = Args {
        concept: None, // defaults to root (138875005)
        sample: 50,
        tree: false,
        depth: 2,
        format: OutputFormat::Text,
        build_tct: true, // the flag under test
        db: Some(db.clone()),
    };
    size::run(args).unwrap();

    // Verify the TCT was rebuilt.
    {
        let conn = Connection::open(&db).unwrap();
        let has_tct: bool = conn
            .query_row(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name='concept_ancestors'",
                [],
                |_| Ok(true),
            )
            .unwrap_or(false);
        assert!(has_tct, "concept_ancestors table should have been rebuilt");

        let row_count: i64 = conn
            .query_row("SELECT COUNT(*) FROM concept_ancestors", [], |r| r.get(0))
            .unwrap();
        assert!(row_count > 0, "concept_ancestors should contain rows");
    }
}
