// SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

#![cfg(feature = "cli")]

//! Full-pipeline end-to-end tests over a committed, fully-synthetic RF2 snapshot
//! (`tests/fixtures/rf2/`, generated by `generate.py` - not real SNOMED content,
//! so licence-free). Each test runs the real `sct ndjson` and `sct sqlite`
//! commands over the fixture, then asserts across every feature: active
//! filtering, GB/US dialect preferred terms, hierarchy, typed relationships,
//! CTV3 maps, refset membership, FTS5 search, the transitive-closure table, and
//! ECL (hierarchy / boolean / refset / attribute refinement).

use rusqlite::Connection;
use sct_rs::commands::ndjson::{self, RefsetMode};
use sct_rs::commands::sqlite;
use sct_rs::commands::{size, tct};
use sct_rs::ecl;
use sct_rs::schema::{ConceptRecord, RefsetMemberRecord, RefsetSidecarProvenance};
use std::path::{Path, PathBuf};

const EXAMPLE_REFSET: &str = "991381000000107";

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/rf2/SnomedCT_SyntheticTest_PRODUCTION_20260101T120000Z")
}

/// Build NDJSON (at `locale`) and a SQLite DB (with the transitive-closure
/// table) from the fixture into a fresh tempdir. Returns the guard plus paths.
fn build(locale: &str) -> (tempfile::TempDir, PathBuf, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    let db = dir.path().join("syn.db");

    ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: locale.to_string(),
        output: Some(ndjson.clone()),
        include_inactive: false,
        refsets: RefsetMode::Simple,
    })
    .unwrap();

    sqlite::run(sqlite::Args {
        input: ndjson.clone(),
        output: Some(db.clone()),
        transitive_closure: true,
        include_self: false,
    })
    .unwrap();

    (dir, ndjson, db)
}

/// As [`build`] but with `--refsets all`, so payload-bearing map/AttributeValue
/// members and Association history load.
fn build_all(locale: &str) -> (tempfile::TempDir, PathBuf, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    let db = dir.path().join("syn.db");
    ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: locale.to_string(),
        output: Some(ndjson.clone()),
        include_inactive: false,
        refsets: RefsetMode::All,
    })
    .unwrap();
    sqlite::run(sqlite::Args {
        input: ndjson.clone(),
        output: Some(db.clone()),
        transitive_closure: false,
        include_self: false,
    })
    .unwrap();
    (dir, ndjson, db)
}

fn read_records(path: &Path) -> Vec<ConceptRecord> {
    std::fs::read_to_string(path)
        .unwrap()
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.contains("sct_provenance"))
        .map(|l| serde_json::from_str(l).unwrap())
        .collect()
}

fn record<'a>(records: &'a [ConceptRecord], id: &str) -> &'a ConceptRecord {
    records.iter().find(|r| r.id == id).expect("record present")
}

fn read_refset_records(path: &Path) -> (RefsetSidecarProvenance, Vec<RefsetMemberRecord>) {
    let text = std::fs::read_to_string(path).unwrap();
    let mut lines = text.lines().filter(|line| !line.trim().is_empty());
    let provenance = serde_json::from_str(lines.next().expect("refset provenance header")).unwrap();
    let records = lines
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    (provenance, records)
}

/// Evaluate ECL and return the matching SCTIDs, sorted for comparison.
fn ecl(db: &Path, expr: &str) -> Vec<String> {
    let mut v = ecl::expand_path(db, expr).unwrap();
    v.sort();
    v
}

#[test]
fn extended_maps_load_into_crossmaps() {
    let (_d, ndjson, db) = build_all("en-GB");

    // NDJSON: MI carries an ICD-10 crossmap with its advice preserved.
    let records = read_records(&ndjson);
    let mi = record(&records, "22298006");
    let icd = mi
        .crossmaps
        .iter()
        .find(|m| m.system == "icd10")
        .expect("MI has an ICD-10 crossmap");
    assert_eq!(icd.code, "I219");
    assert_eq!(icd.advice, "ALWAYS I21.9");

    // DB: forward (SNOMED -> ICD-10 / OPCS-4) and reverse (code -> SNOMED).
    let conn = Connection::open(&db).unwrap();
    let ctv3: String = conn
        .query_row(
            "SELECT target_code FROM crossmaps
             WHERE source_system='ctv3' AND source_code='X200' AND target_system='snomed'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(ctv3, "22298006");
    let alternatives: Vec<(String, i64)> = conn
        .prepare(
            "SELECT target_code, map_priority FROM crossmaps
             WHERE source_code='22298006' AND target_system='icd10'
               AND target_code='I219'
             ORDER BY map_priority",
        )
        .unwrap()
        .query_map([], |row| Ok((row.get(0)?, row.get(1)?)))
        .unwrap()
        .collect::<rusqlite::Result<_>>()
        .unwrap();
    assert_eq!(alternatives, vec![("I219".into(), 1), ("I219".into(), 2)]);
    let opcs: String = conn
        .query_row(
            "SELECT target_code FROM crossmaps WHERE source_code='80146002' AND target_system='opcs4'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(opcs, "H011");
    // Reverse: which SNOMED concept maps to ICD-10 E10.9 (Type 1 diabetes)?
    let snomed: String = conn
        .query_row(
            "SELECT source_code FROM crossmaps WHERE target_system='icd10' AND target_code='E109'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(snomed, "46635009");
}

#[test]
fn payload_refsets_round_trip_without_contaminating_simple_membership() {
    let (_d, ndjson, db) = build_all("en-GB");
    let sidecar = ndjson::refset_sidecar_path(&ndjson);
    assert!(sidecar.exists(), "payload refset sidecar should be written");

    let (sidecar_provenance, records) = read_refset_records(&sidecar);
    let main_text = std::fs::read_to_string(&ndjson).unwrap();
    let main_provenance = sct_rs::provenance::try_parse_ndjson_line(
        main_text.lines().next().expect("main provenance header"),
    )
    .unwrap();
    assert_eq!(sidecar_provenance.source, main_provenance);
    let manifest = main_provenance
        .companion(sct_rs::provenance::COMPANION_PAYLOAD_REFSETS)
        .expect("main provenance declares payload-refset companion");
    assert_eq!(manifest.record_count, 15);
    assert_eq!(
        manifest.content_fingerprint,
        sidecar_provenance.refset_fingerprint
    );

    let complex: Vec<_> = records
        .iter()
        .filter_map(|record| match record {
            RefsetMemberRecord::ComplexMap(member) => Some(member),
            _ => None,
        })
        .collect();
    let extended: Vec<_> = records
        .iter()
        .filter_map(|record| match record {
            RefsetMemberRecord::ExtendedMap(member) => Some(member),
            _ => None,
        })
        .collect();
    let attributes: Vec<_> = records
        .iter()
        .filter_map(|record| match record {
            RefsetMemberRecord::AttributeValue(member) => Some(member),
            _ => None,
        })
        .collect();
    assert_eq!(complex.len(), 2);
    assert_eq!(extended.len(), 10);
    assert_eq!(attributes.len(), 3);

    let complex_active = complex.iter().find(|member| member.active).unwrap();
    assert_eq!(complex_active.map_rule, "IFA 246075003");
    assert_eq!(complex_active.map_advice, "CHECK LEGACY CLASSIFICATION");
    assert_eq!(complex_active.map_target, "LEGACY-01");
    assert!(complex.iter().any(|member| !member.active));

    assert!(extended
        .iter()
        .any(|member| member.refset_id == "991391000000109"));
    assert!(extended.iter().any(|member| member.map_target.is_empty()));
    let category = extended
        .iter()
        .find(|member| member.id == "30000000-0000-4000-8000-000000000001")
        .expect("International mapCategoryId member");
    assert_eq!(category.map_category_id.as_deref(), Some("447637006"));
    assert_eq!(category.map_block, None);
    assert!(extended.iter().any(|member| !member.active));

    let inactivation = attributes
        .iter()
        .find(|member| member.active)
        .expect("active concept inactivation indicator");
    assert_eq!(inactivation.refset_id, "900000000000489007");
    assert_eq!(inactivation.referenced_component_id, "9468002");
    assert_eq!(inactivation.value_id, "900000000000482003");
    assert!(attributes.iter().any(|member| !member.active));
    assert!(attributes.iter().any(|member| {
        member.refset_id == "900000000000490003" && member.referenced_component_id == "5000001"
    }));

    let conn = Connection::open(&db).unwrap();
    let sqlite_provenance = sct_rs::provenance::read_sqlite(&conn)
        .unwrap()
        .expect("SQLite provenance");
    assert_eq!(sqlite_provenance.companions, main_provenance.companions);
    let count = |table: &str| -> i64 {
        conn.query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
            row.get(0)
        })
        .unwrap()
    };
    assert_eq!(count("complex_map_refset_members"), 2);
    assert_eq!(count("extended_map_refset_members"), 10);
    assert_eq!(count("attribute_value_refset_members"), 3);
    assert_eq!(count("refset_members"), 2);

    let complex_sqlite: (
        String,
        String,
        i64,
        String,
        String,
        String,
        i64,
        i64,
        String,
        String,
        String,
        String,
    ) = conn
        .query_row(
            "SELECT id, effective_time, active, module_id, refset_id,
                    referenced_component_id, map_group, map_priority, map_rule,
                    map_advice, map_target, correlation_id
             FROM complex_map_refset_members
             WHERE id = '10000000-0000-4000-8000-000000000001'",
            [],
            |row| {
                Ok((
                    row.get(0)?,
                    row.get(1)?,
                    row.get(2)?,
                    row.get(3)?,
                    row.get(4)?,
                    row.get(5)?,
                    row.get(6)?,
                    row.get(7)?,
                    row.get(8)?,
                    row.get(9)?,
                    row.get(10)?,
                    row.get(11)?,
                ))
            },
        )
        .unwrap();
    assert_eq!(
        complex_sqlite,
        (
            "10000000-0000-4000-8000-000000000001".into(),
            "20260101".into(),
            1,
            "900000000000207008".into(),
            "991401000000101".into(),
            "22298006".into(),
            1,
            1,
            "IFA 246075003".into(),
            "CHECK LEGACY CLASSIFICATION".into(),
            "LEGACY-01".into(),
            "447561005".into(),
        )
    );

    let extended_tail: (Option<String>, Option<i64>) = conn
        .query_row(
            "SELECT map_category_id, map_block FROM extended_map_refset_members
             WHERE id = '30000000-0000-4000-8000-000000000001'",
            [],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .unwrap();
    assert_eq!(extended_tail, (Some("447637006".into()), None));
    assert_eq!(
        conn.query_row(
            "SELECT COUNT(*) FROM extended_map_refset_members WHERE active = 0",
            [],
            |row| row.get::<_, i64>(0),
        )
        .unwrap(),
        1
    );

    let reason: String = conn
        .query_row(
            "SELECT value_id FROM attribute_value_refset_members
             WHERE active = 1 AND refset_id = '900000000000489007'
               AND referenced_component_id = '9468002'",
            [],
            |row| row.get(0),
        )
        .unwrap();
    assert_eq!(reason, "900000000000482003");
    let attribute_envelope: (String, String, i64, String, String, String, String) = conn
        .query_row(
            "SELECT id, effective_time, active, module_id, refset_id,
                    referenced_component_id, value_id
             FROM attribute_value_refset_members
             WHERE id = '20000000-0000-4000-8000-000000000003'",
            [],
            |row| {
                Ok((
                    row.get(0)?,
                    row.get(1)?,
                    row.get(2)?,
                    row.get(3)?,
                    row.get(4)?,
                    row.get(5)?,
                    row.get(6)?,
                ))
            },
        )
        .unwrap();
    assert_eq!(
        attribute_envelope,
        (
            "20000000-0000-4000-8000-000000000003".into(),
            "20260101".into(),
            1,
            "900000000000207008".into(),
            "900000000000490003".into(),
            "5000001".into(),
            "900000000000482003".into(),
        )
    );
    let unclassified_projection: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM crossmaps WHERE map_refset = '991391000000109'",
            [],
            |row| row.get(0),
        )
        .unwrap();
    assert_eq!(unclassified_projection, 0);
}

#[test]
fn tampered_refset_sidecar_rolls_back_sqlite_rebuild() {
    let (_d, ndjson, db) = build_all("en-GB");
    let sidecar = ndjson::refset_sidecar_path(&ndjson);
    let original = std::fs::read_to_string(&sidecar).unwrap();
    let tampered = original.replacen("900000000000483008", "900000000000483009", 1);
    assert_ne!(tampered, original, "fixture value should be present");
    std::fs::write(&sidecar, tampered).unwrap();

    let error = sqlite::run(sqlite::Args {
        input: ndjson,
        output: Some(db.clone()),
        transitive_closure: false,
        include_self: false,
    })
    .unwrap_err();
    assert!(
        format!("{error:#}").contains("refset sidecar fingerprint mismatch"),
        "unexpected error: {error:#}"
    );

    let conn = Connection::open(db).unwrap();
    let count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM attribute_value_refset_members",
            [],
            |row| row.get(0),
        )
        .unwrap();
    assert_eq!(
        count, 3,
        "failed rebuild must preserve the previous database"
    );
}

#[test]
fn missing_declared_refset_sidecar_rolls_back_sqlite_rebuild() {
    let (_d, ndjson, db) = build_all("en-GB");
    std::fs::remove_file(ndjson::refset_sidecar_path(&ndjson)).unwrap();

    let error = sqlite::run(sqlite::Args {
        input: ndjson,
        output: Some(db.clone()),
        transitive_closure: false,
        include_self: false,
    })
    .unwrap_err();
    assert!(
        format!("{error:#}").contains("declares a payload-refset companion"),
        "unexpected error: {error:#}"
    );

    let conn = Connection::open(db).unwrap();
    let count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM attribute_value_refset_members",
            [],
            |row| row.get(0),
        )
        .unwrap();
    assert_eq!(
        count, 3,
        "failed rebuild must preserve the previous database"
    );
}

#[test]
fn tampered_history_sidecar_rolls_back_sqlite_rebuild() {
    let (_d, ndjson, db) = build_all("en-GB");
    let sidecar = ndjson::history_sidecar_path(&ndjson);
    let original = std::fs::read_to_string(&sidecar).unwrap();
    let tampered = original.replacen("195967001", "195967002", 1);
    assert_ne!(tampered, original, "fixture target should be present");
    std::fs::write(&sidecar, tampered).unwrap();

    let error = sqlite::run(sqlite::Args {
        input: ndjson,
        output: Some(db.clone()),
        transitive_closure: false,
        include_self: false,
    })
    .unwrap_err();
    assert!(
        format!("{error:#}").contains("history companion fingerprint mismatch"),
        "unexpected error: {error:#}"
    );

    let conn = Connection::open(db).unwrap();
    let count: i64 = conn
        .query_row("SELECT COUNT(*) FROM concept_history", [], |row| row.get(0))
        .unwrap();
    assert_eq!(count, 2, "failed rebuild must preserve concept history");
}

#[test]
fn simple_rebuild_removes_payload_and_history_sidecars() {
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    let db = dir.path().join("syn.db");
    for refsets in [RefsetMode::All, RefsetMode::Simple] {
        ndjson::run(ndjson::Args {
            rf2_dirs: vec![fixture_dir()],
            locale: "en-GB".to_string(),
            output: Some(ndjson.clone()),
            include_inactive: false,
            refsets,
        })
        .unwrap();
        sqlite::run(sqlite::Args {
            input: ndjson.clone(),
            output: Some(db.clone()),
            transitive_closure: false,
            include_self: false,
        })
        .unwrap();
        if refsets == RefsetMode::All {
            assert!(ndjson::refset_sidecar_path(&ndjson).exists());
            assert!(ndjson::history_sidecar_path(&ndjson).exists());
        }
    }
    assert!(!ndjson::refset_sidecar_path(&ndjson).exists());
    assert!(!ndjson::history_sidecar_path(&ndjson).exists());
    let conn = Connection::open(db).unwrap();
    for table in [
        "complex_map_refset_members",
        "extended_map_refset_members",
        "attribute_value_refset_members",
        "concept_history",
    ] {
        let count: i64 = conn
            .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
                row.get(0)
            })
            .unwrap();
        assert_eq!(count, 0, "{table} should be cleared by the simple rebuild");
    }
}

#[test]
fn failed_companion_publish_preserves_existing_main() {
    let (_dir, ndjson, _db) = build("en-GB");
    let original = std::fs::read(&ndjson).unwrap();
    let refset_sidecar = ndjson::refset_sidecar_path(&ndjson);
    std::fs::create_dir(&refset_sidecar).unwrap();

    let error = ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: "en-GB".to_string(),
        output: Some(ndjson.clone()),
        include_inactive: false,
        refsets: RefsetMode::All,
    })
    .unwrap_err();

    assert!(
        format!("{error:#}").contains("payload-refset companion"),
        "unexpected error: {error:#}"
    );
    assert_eq!(
        std::fs::read(ndjson).unwrap(),
        original,
        "failed companion publication must not replace the main artefact"
    );
}

#[test]
fn failed_later_companion_publish_rolls_back_earlier_companion() {
    let (_dir, ndjson, _db) = build_all("en-GB");
    let refset_sidecar = ndjson::refset_sidecar_path(&ndjson);
    let history_sidecar = ndjson::history_sidecar_path(&ndjson);
    let original_main = std::fs::read(&ndjson).unwrap();
    let original_refsets = std::fs::read(&refset_sidecar).unwrap();
    std::fs::remove_file(&history_sidecar).unwrap();
    std::fs::create_dir(&history_sidecar).unwrap();

    let error = ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: "en-GB".to_string(),
        output: Some(ndjson.clone()),
        include_inactive: false,
        refsets: RefsetMode::All,
    })
    .unwrap_err();

    assert!(
        format!("{error:#}").contains("history companion"),
        "unexpected error: {error:#}"
    );
    assert_eq!(std::fs::read(ndjson).unwrap(), original_main);
    assert_eq!(
        std::fs::read(refset_sidecar).unwrap(),
        original_refsets,
        "a later publication failure must restore an earlier companion"
    );
}

#[test]
fn all_mode_refuses_to_silently_drop_companion_streams_on_stdout() {
    let error = ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: "en-GB".to_string(),
        output: Some(PathBuf::from("-")),
        include_inactive: false,
        refsets: RefsetMode::All,
    })
    .unwrap_err();
    assert!(
        error.to_string().contains("require companion NDJSON files"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn simple_mode_omits_extended_maps() {
    // Default `--refsets simple` loads SimpleMap rows into crossmaps, but must
    // NOT load the heavy ExtendedMap / history data.
    let (_d, _ndjson, db) = build("en-GB");
    let conn = Connection::open(&db).unwrap();
    let simple_maps: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM crossmaps WHERE source_system='ctv3' AND target_system='snomed'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert!(simple_maps > 0);
    let extended_maps: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM crossmaps WHERE source_system='snomed' AND target_system IN ('icd10', 'opcs4')",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(extended_maps, 0);
    let hist: i64 = conn
        .query_row("SELECT COUNT(*) FROM concept_history", [], |r| r.get(0))
        .unwrap();
    assert_eq!(hist, 0);
    for table in [
        "complex_map_refset_members",
        "extended_map_refset_members",
        "attribute_value_refset_members",
    ] {
        let count: i64 = conn
            .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
                row.get(0)
            })
            .unwrap();
        assert_eq!(count, 0, "{table} should remain empty in simple mode");
    }
}

#[test]
fn concept_history_loads_from_associations() {
    let (_d, ndjson, db) = build_all("en-GB");

    // The history sidecar is written next to the NDJSON.
    let sidecar = ndjson.with_file_name("syn.history.ndjson");
    assert!(sidecar.exists(), "history sidecar should be written");

    // Inactive 9468002 forwards to Asthma (same_as) and MI (replaced_by).
    let conn = Connection::open(&db).unwrap();
    let mut rows: Vec<(String, String)> = conn
        .prepare("SELECT association, target_id FROM concept_history WHERE source_id='9468002'")
        .unwrap()
        .query_map([], |r| Ok((r.get(0)?, r.get(1)?)))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    rows.sort();
    assert_eq!(
        rows,
        vec![
            ("replaced_by".to_string(), "22298006".to_string()),
            ("same_as".to_string(), "195967001".to_string()),
        ]
    );
}

/// ECL history supplements (`spec/ecl.md` §5, ECL specification §6.11). The
/// fixture's inactive 9468002 is `SAME AS` Asthma and `REPLACED BY` MI, so the
/// three profiles are distinguishable: `MIN` follows only `SAME AS`, while
/// `MOD` and `MAX` also follow `REPLACED BY`.
#[test]
fn history_supplement_profiles_select_different_associations() {
    let (_d, _ndjson, db) = build_all("en-GB");

    // Without a supplement, the retired concept is unreachable: it has been
    // stripped of its parents, so no hierarchy query finds it.
    assert_eq!(ecl(&db, "<<195967001"), vec!["195967001"]);

    // MIN follows SAME AS only - reachable from Asthma, not from MI.
    assert_eq!(
        ecl(&db, "195967001 {{ + HISTORY-MIN }}"),
        vec!["195967001", "9468002"]
    );
    assert_eq!(ecl(&db, "22298006 {{ + HISTORY-MIN }}"), vec!["22298006"]);

    // MOD and MAX add REPLACED BY, so MI reaches it too.
    for supplement in [
        "+ HISTORY-MOD",
        "+ HISTORY-MAX",
        "+HISTORY",
        "+ HISTORY (*)",
    ] {
        assert_eq!(
            ecl(&db, &format!("22298006 {{{{ {supplement} }}}}")),
            vec!["22298006", "9468002"],
            "supplement {supplement} should follow the REPLACED BY association"
        );
    }

    // An explicit reference set list behaves like the profile that contains it.
    assert_eq!(
        ecl(&db, "22298006 {{ + HISTORY (900000000000526001) }}"),
        vec!["22298006", "9468002"]
    );
    assert_eq!(
        ecl(&db, "22298006 {{ + HISTORY (900000000000527005) }}"),
        vec!["22298006"]
    );
}

/// The supplement applies to whatever sub-expression precedes it, so it
/// composes with hierarchy queries and binds to the nearest focus.
#[test]
fn history_supplement_composes_with_the_rest_of_the_expression() {
    let (_d, _ndjson, db) = build_all("en-GB");

    // Every clinical finding, plus the inactive concepts associated with any
    // of them: the retired concept arrives via its SAME AS to Asthma.
    let all = ecl(&db, "<404684003 {{ + HISTORY-MIN }}");
    assert!(all.contains(&"9468002".to_string()), "{all:?}");

    // Binds to the nearest focus, like a refinement: the supplement here
    // applies to `22298006` alone, and MIN does not reach the retired concept
    // from there.
    assert_eq!(
        ecl(&db, "195967001 OR 22298006 {{ + HISTORY-MIN }}"),
        vec!["195967001", "22298006"]
    );
    // Parenthesised, it covers both.
    assert_eq!(
        ecl(&db, "(195967001 OR 22298006) {{ + HISTORY-MIN }}"),
        vec!["195967001", "22298006", "9468002"]
    );
}

/// Filters other than history supplements are refused by name, and an unknown
/// profile is named too - `spec/ecl.md` promises a clear "unsupported ECL
/// construct" message rather than a character-level parse error.
#[test]
fn unsupported_filters_and_profiles_are_refused_by_name() {
    let (_d, _ndjson, db) = build_all("en-GB");

    let error = format!(
        "{:#}",
        ecl::expand_path(&db, "<<73211009 {{ term = \"diabetes\" }}").unwrap_err()
    );
    assert!(
        error.contains("unsupported ECL construct") && error.contains("history supplements"),
        "unexpected error: {error}"
    );

    let error = format!(
        "{:#}",
        ecl::expand_path(&db, "<<73211009 {{ + HISTORY-EVERYTHING }}").unwrap_err()
    );
    assert!(
        error.contains("unknown history supplement profile"),
        "unexpected error: {error}"
    );
}

#[test]
fn pipeline_filters_inactive_concepts() {
    let (_d, ndjson, _db) = build("en-GB");
    let records = read_records(&ndjson);
    // 23 concepts in the fixture, 1 inactive (9468002) -> 22 active records.
    assert_eq!(records.len(), 22);
    assert!(records.iter().all(|r| r.id != "9468002"));
}

#[test]
fn include_inactive_emits_inactive_concepts() {
    // Regression test for `--include-inactive`. The inactive concept 9468002 was
    // dropped at RF2 load time regardless of the flag; it must now appear, with
    // `active = false` and its term fully populated from its (still-active) FSN.
    let dir = tempfile::tempdir().unwrap();
    let ndjson = dir.path().join("syn.ndjson");
    ndjson::run(ndjson::Args {
        rf2_dirs: vec![fixture_dir()],
        locale: "en-GB".to_string(),
        output: Some(ndjson.clone()),
        include_inactive: true,
        refsets: RefsetMode::Simple,
    })
    .unwrap();

    let records = read_records(&ndjson);
    // All 23 fixture concepts now, exactly one of them inactive.
    assert_eq!(records.len(), 23);
    assert_eq!(records.iter().filter(|r| !r.active).count(), 1);

    let inactive = record(&records, "9468002");
    assert!(!inactive.active);
    assert_eq!(inactive.fsn, "Inactive example disorder (disorder)");
    assert_eq!(inactive.preferred_term, "Inactive example disorder");

    // Active concepts are unaffected: every other record is still active.
    assert!(records
        .iter()
        .filter(|r| r.id != "9468002")
        .all(|r| r.active));
}

#[test]
fn sqlite_rebuild_replaces_all_ndjson_derived_data() {
    let dir = tempfile::tempdir().unwrap();
    let inactive_ndjson = dir.path().join("inactive.ndjson");
    let active_ndjson = dir.path().join("active.ndjson");
    let db = dir.path().join("syn.db");

    for (output, include_inactive) in [(&inactive_ndjson, true), (&active_ndjson, false)] {
        ndjson::run(ndjson::Args {
            rf2_dirs: vec![fixture_dir()],
            locale: "en-GB".to_string(),
            output: Some(output.clone()),
            include_inactive,
            refsets: RefsetMode::Simple,
        })
        .unwrap();
    }

    sqlite::run(sqlite::Args {
        input: inactive_ndjson,
        output: Some(db.clone()),
        transitive_closure: true,
        include_self: false,
    })
    .unwrap();

    let active_records = read_records(&active_ndjson);
    let expected_isa: i64 = active_records
        .iter()
        .map(|record| record.parents.len() as i64)
        .sum();
    let expected_relationships: i64 = active_records
        .iter()
        .map(|record| record.relationships.len() as i64)
        .sum();

    for _ in 0..2 {
        sqlite::run(sqlite::Args {
            input: active_ndjson.clone(),
            output: Some(db.clone()),
            transitive_closure: false,
            include_self: false,
        })
        .unwrap();

        let conn = Connection::open(&db).unwrap();
        let count = |query: &str| -> i64 { conn.query_row(query, [], |row| row.get(0)).unwrap() };
        assert_eq!(
            count("SELECT COUNT(*) FROM concepts"),
            active_records.len() as i64
        );
        assert_eq!(count("SELECT COUNT(*) FROM concept_isa"), expected_isa);
        assert_eq!(
            count("SELECT COUNT(*) FROM concept_relationships"),
            expected_relationships
        );
        assert_eq!(
            conn.query_row(
                "SELECT COUNT(*) FROM concepts WHERE active = 0",
                [],
                |row| row.get::<_, i64>(0),
            )
            .unwrap(),
            0
        );
        assert_eq!(
            conn.query_row(
                "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = 'concept_ancestors'",
                [],
                |row| row.get::<_, i64>(0),
            )
            .unwrap(),
            0
        );

        let header = std::fs::read_to_string(&active_ndjson).unwrap();
        let expected_fingerprint = sct_rs::provenance::try_parse_ndjson_line(
            header.lines().next().expect("provenance header"),
        )
        .unwrap()
        .content_fingerprint;
        let actual_fingerprint = sct_rs::provenance::read_sqlite(&conn)
            .unwrap()
            .unwrap()
            .content_fingerprint;
        assert_eq!(actual_fingerprint, expected_fingerprint);
    }
}

#[test]
fn dialect_preferred_terms() {
    let (_g, gb_ndjson, _gdb) = build("en-GB");
    assert_eq!(
        record(&read_records(&gb_ndjson), "80146002").preferred_term,
        "Appendicectomy"
    );

    let (_u, us_ndjson, _udb) = build("en-US");
    assert_eq!(
        record(&read_records(&us_ndjson), "80146002").preferred_term,
        "Appendectomy"
    );
}

#[test]
fn builder_record_shape() {
    let (_d, ndjson, _db) = build("en-GB");
    let records = read_records(&ndjson);

    let mi = record(&records, "22298006");
    assert_eq!(mi.preferred_term, "Myocardial infarction");
    assert_eq!(mi.hierarchy, "Clinical finding");
    assert!(mi.synonyms.contains(&"Heart attack".to_string()));
    assert!(mi.ctv3_codes.contains(&"X200".to_string()));

    // Typed relationships preserved with type SCTID + group (for ECL).
    let has = |t: &str, d: &str| {
        mi.relationships
            .iter()
            .any(|r| r.type_id == t && r.destination_id == d && r.group == 1)
    };
    assert!(has("363698007", "74281007"), "finding site");
    assert!(has("116676008", "55641003"), "associated morphology");

    // Refset membership surfaced on the member records.
    assert!(record(&records, "46635009")
        .refsets
        .contains(&EXAMPLE_REFSET.to_string()));
}

#[test]
fn ecl_hierarchy_boolean_and_refset() {
    let (_d, _ndjson, db) = build("en-GB");

    assert_eq!(ecl(&db, "<<73211009"), ["44054006", "46635009", "73211009"]);
    assert_eq!(ecl(&db, "<73211009"), ["44054006", "46635009"]);
    assert_eq!(
        ecl(&db, ">>46635009"),
        ["138875005", "404684003", "46635009", "73211009"]
    );
    assert_eq!(ecl(&db, "<!73211009"), ["44054006", "46635009"]);
    assert_eq!(ecl(&db, "^991381000000107"), ["44054006", "46635009"]);
    assert_eq!(
        ecl(&db, "<<73211009 MINUS 46635009"),
        ["44054006", "73211009"]
    );
    assert_eq!(ecl(&db, "195967001 OR 22298006"), ["195967001", "22298006"]);
}

#[test]
fn ecl_attribute_refinement() {
    let (_d, _ndjson, db) = build("en-GB");
    // Clinical findings whose finding site is (a descendant-or-self of) Myocardium.
    assert_eq!(
        ecl(&db, "<<404684003 : 363698007 = <<74281007"),
        ["22298006"]
    );
    // Wrong value -> no match.
    assert!(ecl(&db, "<<404684003 : 363698007 = 55641003").is_empty());
}

#[test]
fn sqlite_fts5_maps_relationships_and_tct() {
    let (_d, _ndjson, db) = build("en-GB");
    let conn = Connection::open(&db).unwrap();

    // Definition status survives RF2 -> NDJSON -> SQLite (schema v6).
    let definition_status: String = conn
        .query_row(
            "SELECT definition_status FROM concepts WHERE id = '22298006'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(definition_status, "900000000000074008");

    // FTS5 keyword search: "diabetes" hits the parent + both subtypes.
    let mut stmt = conn
        .prepare(
            "SELECT c.id FROM concepts_fts JOIN concepts c ON concepts_fts.rowid = c.rowid
             WHERE concepts_fts MATCH '\"diabetes\"' ORDER BY c.id",
        )
        .unwrap();
    let mut ids: Vec<String> = stmt
        .query_map([], |r| r.get::<_, String>(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    ids.sort();
    assert_eq!(ids, ["44054006", "46635009", "73211009"]);

    // CTV3 reverse map.
    let mapped: String = conn
        .query_row(
            "SELECT concept_id FROM concept_maps WHERE code = 'X200' AND terminology = 'ctv3'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(mapped, "22298006");

    // Typed relationships table (schema v4): MI has its 2 attributes.
    let rel_count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM concept_relationships WHERE source_id = '22298006'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(rel_count, 2);

    // Transitive closure: Type 1 DM has 3 ancestors (DM, Clinical finding, root).
    let anc_count: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM concept_ancestors WHERE descendant_id = '46635009'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(anc_count, 3);

    // Refset membership.
    let mut stmt = conn
        .prepare("SELECT referenced_component_id FROM refset_members WHERE refset_id = ?1 ORDER BY referenced_component_id")
        .unwrap();
    let members: Vec<String> = stmt
        .query_map([EXAMPLE_REFSET], |r| r.get::<_, String>(0))
        .unwrap()
        .map(|r| r.unwrap())
        .collect();
    assert_eq!(members, ["44054006", "46635009"]);
}

#[test]
fn size_estimate_for_root() {
    let (_d, _ndjson, db) = build("en-GB");
    let conn = Connection::open(&db).unwrap();

    let est = size::estimate_sizes(&conn, "138875005", 50).unwrap();
    assert_eq!(est.subtree_count, est.total_count);
    assert_eq!(est.pct(), 100.0);
    assert!(est.avg_ndjson_bytes > 0);
    assert_eq!(est.sqlite_total, est.total_db_bytes);
    assert!(est.ndjson_total > 0);
}

#[test]
fn size_estimate_with_self_inclusive_transitive_closure_table() {
    let (_d, _ndjson, db) = build_all("en-GB");
    let mut conn = Connection::open(&db).unwrap();
    tct::build(&mut conn, true).unwrap();

    let est = size::estimate_sizes(&conn, "73211009", 50).unwrap();
    assert_eq!(est.subtree_count, 3);
}

/// Regression test: without a transitive-closure table, the subtree count
/// must fall back to a recursive CTE rather than erroring out. It previously
/// propagated SQLite's "query returned no rows" through `?` instead of
/// treating a missing `concept_ancestors` table as `has_tct = false`.
#[test]
fn size_estimate_without_transitive_closure_table() {
    let (_d, _ndjson, db) = build_all("en-GB");
    let conn = Connection::open(&db).unwrap();

    let has_tct: bool = conn
        .query_row(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='concept_ancestors'",
            [],
            |_| Ok(true),
        )
        .unwrap_or(false);
    assert!(
        !has_tct,
        "fixture db unexpectedly has a transitive-closure table"
    );

    // Diabetes mellitus (73211009) plus its two children = 3 concepts,
    // matching the `<<73211009` ECL result asserted elsewhere in this suite.
    let est = size::estimate_sizes(&conn, "73211009", 50).unwrap();
    assert_eq!(est.subtree_count, 3);
}

#[test]
fn size_builds_tct_when_missing() {
    use sct_rs::commands::size::{self, Args};
    use sct_rs::output::OutputFormat;

    let (_d, _ndjson, db) = build("en-GB");

    // Drop the TCT to simulate a database without one.
    {
        let conn = Connection::open(&db).unwrap();
        conn.execute("DROP TABLE concept_ancestors", []).unwrap();
    }

    // Run `sct size --build-tct`, which should rebuild the TCT and proceed.
    let args = Args {
        concept: None, // defaults to root (138875005)
        sample: 50,
        tree: false,
        depth: 2,
        format: OutputFormat::Text,
        build_tct: true, // the flag under test
        db: Some(db.clone()),
    };
    size::run(args).unwrap();

    // Verify the TCT was rebuilt.
    {
        let conn = Connection::open(&db).unwrap();
        let has_tct: bool = conn
            .query_row(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name='concept_ancestors'",
                [],
                |_| Ok(true),
            )
            .unwrap_or(false);
        assert!(has_tct, "concept_ancestors table should have been rebuilt");

        let row_count: i64 = conn
            .query_row("SELECT COUNT(*) FROM concept_ancestors", [], |r| r.get(0))
            .unwrap();
        assert!(row_count > 0, "concept_ancestors should contain rows");
    }
}

// ---------------------------------------------------------------------------
// R16: `sct mcp` tool handlers, driven through the JSON-RPC dispatcher over the
// committed synthetic fixture (the same RF2 -> NDJSON -> SQLite DB the rest of
// this file builds). Exercises the tool layer end-to-end, not just the SQL.
// ---------------------------------------------------------------------------
mod mcp_tools {
    use super::{build, EXAMPLE_REFSET};
    use rusqlite::Connection;
    use sct_rs::commands::mcp;
    use serde_json::json;

    /// Call one tool through the domain-level MCP adapter and return its JSON.
    /// Separate process tests cover the protocol lifecycle and wire format.
    fn tool_text(conn: &Connection, name: &str, arguments: serde_json::Value) -> String {
        let result = mcp::call_tool_for_test(conn, name, arguments)
            .unwrap_or_else(|error| panic!("{name} failed: {error:#}"));
        serde_json::to_string_pretty(&result).unwrap()
    }

    #[test]
    fn search_matches_preferred_terms_and_synonyms() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();

        // Preferred-term / FSN match: "diabetes" -> the two diabetes children.
        let out = tool_text(&conn, "snomed_search", json!({ "query": "diabetes" }));
        assert!(
            out.contains("46635009"),
            "diabetes search missing type 1: {out}"
        );
        assert!(
            out.contains("44054006"),
            "diabetes search missing type 2: {out}"
        );

        // Synonym match: "heart" is only in MI's synonym "Heart attack".
        let out = tool_text(&conn, "snomed_search", json!({ "query": "heart" }));
        assert!(out.contains("22298006"), "synonym search missing MI: {out}");

        let out = tool_text(
            &conn,
            "snomed_search",
            json!({ "query": "unmatched \" quote" }),
        );
        assert!(out.contains("No results found"), "unmatched quote: {out}");
    }

    #[test]
    fn concept_returns_detail() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();
        let out = tool_text(&conn, "snomed_concept", json!({ "id": "22298006" }));
        assert!(out.contains("Myocardial infarction"), "{out}");
        assert!(out.contains("Clinical finding"), "{out}");
    }

    #[test]
    fn children_and_ancestors_walk_the_isa_graph() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();

        // Diabetes mellitus (73211009) -> type 1 (46635009) + type 2 (44054006).
        let kids = tool_text(&conn, "snomed_children", json!({ "id": "73211009" }));
        assert!(
            kids.contains("46635009") && kids.contains("44054006"),
            "children: {kids}"
        );

        // Type 1 DM (46635009) -> ancestors include Diabetes mellitus (73211009).
        let anc = tool_text(&conn, "snomed_ancestors", json!({ "id": "46635009" }));
        assert!(anc.contains("73211009"), "ancestors: {anc}");
    }

    #[test]
    fn hierarchy_lists_members() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();
        let out = tool_text(
            &conn,
            "snomed_hierarchy",
            json!({ "hierarchy": "Clinical finding" }),
        );
        assert!(out.contains("22298006"), "hierarchy members: {out}");
    }

    #[test]
    fn map_ctv3_code_to_snomed() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();
        let out = tool_text(
            &conn,
            "snomed_map",
            json!({ "code": "X200", "terminology": "ctv3" }),
        );
        assert!(out.contains("22298006"), "ctv3 X200 -> MI: {out}");
    }

    #[test]
    fn refsets_and_members() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();

        let refsets = tool_text(&conn, "snomed_refsets", json!({}));
        assert!(refsets.contains(EXAMPLE_REFSET), "refsets list: {refsets}");

        let members = tool_text(
            &conn,
            "snomed_refset_members",
            json!({ "refset_id": EXAMPLE_REFSET }),
        );
        assert!(
            members.contains("46635009") && members.contains("44054006"),
            "refset members: {members}"
        );
    }

    #[test]
    fn refset_compare_and_profile() {
        let (_d, _n, db) = build("en-GB");
        let conn = Connection::open(&db).unwrap();

        // Comparing the refset against itself: everything is in-both, nothing
        // is only-in-a/only-in-b - still exercises the full tool round trip
        // (the fixture only carries one loaded Simple refset).
        let cmp = tool_text(
            &conn,
            "snomed_refset_compare",
            json!({ "refset_id_a": EXAMPLE_REFSET, "refset_id_b": EXAMPLE_REFSET }),
        );
        assert!(
            cmp.contains("46635009") && cmp.contains("44054006"),
            "refset compare: {cmp}"
        );
        let parsed: serde_json::Value = serde_json::from_str(&cmp).unwrap();
        assert_eq!(parsed["only_in_a"]["count"], 0, "compare: {cmp}");
        assert_eq!(parsed["only_in_b"]["count"], 0, "compare: {cmp}");
        assert_eq!(parsed["in_both"]["count"], 2, "compare: {cmp}");

        // Type 1 + type 2 diabetes are both "Clinical finding".
        let profile = tool_text(
            &conn,
            "snomed_refset_profile",
            json!({ "refset_id": EXAMPLE_REFSET }),
        );
        assert!(
            profile.contains("Clinical finding") && profile.contains('2'),
            "refset profile: {profile}"
        );
    }
}
