# SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
# SPDX-License-Identifier: AGPL-3.0-or-later

from __future__ import annotations

from os import PathLike
from typing import Any, Literal

_Terminology = Literal["snomed", "read2", "ctv3", "icd10", "opcs4"]
_Subsumption = Literal["equivalent", "subsumes", "subsumed_by", "not_subsumed"]

class SctError(Exception): ...
class DatabaseError(SctError): ...
class QueryError(SctError): ...
class ValidationError(SctError): ...

class Snomed:
    def __init__(self, path: str | PathLike[str]) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Snomed: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def provenance(self) -> dict[str, Any] | None: ...
    def refsets(self) -> list[dict[str, Any]]: ...
    def refset(self, refset_id: str) -> dict[str, Any] | None: ...
    def refset_members(self, refset_id: str, limit: int | None = None) -> list[dict[str, Any]]: ...
    def history(self, concept_id: str) -> list[dict[str, Any]]: ...
    def concept(self, concept_id: str) -> dict[str, Any] | None: ...
    def concepts(self, concept_ids: list[str]) -> list[dict[str, Any] | None]: ...
    def search(self, query: str, limit: int = 20, *, hierarchy: str | None = None, literal: bool = False) -> list[dict[str, Any]]: ...
    def expand(self, expression: str) -> list[str]: ...
    def children(self, concept_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    def ancestors(self, concept_id: str) -> list[dict[str, Any]]: ...
    def descendants(self, concept_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    def subsumes(self, left: str, right: str) -> _Subsumption: ...
    def map(self, source: _Terminology, code: str, target: _Terminology, *, forward_history: bool = False) -> list[dict[str, Any]]: ...
    def map_many(self, source: _Terminology, codes: list[str], target: _Terminology, *, forward_history: bool = False) -> list[list[dict[str, Any]]]: ...
